config/routes.rb
Rails.application.routes.draw do

  root to: "flats#index"

    resources :flats do # generates all the routes
      collection do
        get :top  #/flats/top  flats#top
      end

      # member do
      #   # everything here it's going to be /flats/:id/...
      #   get :desciption # it's the same as `get '/flats/:id/description', to: 'restaurants#chef'`
      # end

      # when I use resources, I generate all the rest routes
      resources :reviews, only: [ :create, :destroy ]
      # POST '/flats/:flat_id/reviews/:id', to: 'reviews#create'
      # DELETE '/flats/:flat_id/reviews/:id', to: 'reviews#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :flat
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end


  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.create(flat_params)
    redirect_to root_path

  end

  def destroy
    @flat = Flat.find(params[:id].to_i)

    @flat.destroy
    redirect_to root_path
  end

  def show
    @flat = Flat.find(params[:id].to_i)
    @review = Review.new
  end

  def edit
    @flat = Flat.find(params[:id].to_i)
  end

  def update
    @flat = Flat.find(params[:id].to_i)
    if @flat.update(flat_params)
      #redirect_to @flat, notice: 'Flat was successfully updated.'
      redirect_to flat_path(@flat.id)
    else
      render :edit
    end
  end


  # def top
  # end

  private
  def flat_params
    params.require(:flat).permit(:name, :description, :address, :price_per_night, :number_of_guests)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @flat = Flat.find(params[:flat_id])
    @review = Review.new(review_params)
    @review.flat = @flat
    @review.save

    redirect_to flat_path(@flat.id)
  end

  def destroy
    @flat = Flat.find(params[:flat_id])
    @review = Review.find(params[:id])
    @review.delete

    redirect_to flat_path(@flat.id)
  end

  private
  def review_params
    params.require(:review).permit(:rating, :content)
  end
end
§

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<h1>Edit Flat's Information</h1>

<%= render 'form', flat: @flat %>


<%= link_to 'Back', flats_path %>

app/views/flats/index.html.erb
    <div class="banner">
      <span class="banner-content">
        <h1>Welcome to Airbnb - MVP!</p>
          <%= link_to "ADD A NEW PLACE!", new_flat_path, class: "btn-medium btn-white"%>
      </span>
    </div>

<%@flats.each do |flat|%>

  <div class="product">
    <div class="product-upvotes">
      <!-- i.fa.fa-caret-up -->
      <i class="fa fa-caret-up"></i>
      <p>29</p>
    </div>
    <img src="https://source.unsplash.com/random/250x250" alt="">
    <div class="product-description">
     <%= link_to flat_path(flat.id) do %>
      <h3><%= flat.name %></h3>
        <%end%>
      <p><%= flat.description %>/p>
    </div>
    <ul class="list-inline">
      <!-- (li>a)*3 -->

      <li><%= link_to "View", flat_path(flat.id), class: "btn-small"%>
      </li>
      <li><%= link_to flat_path(flat.id), method: :delete do %>
        <i class="fas fa-trash"></i>
      <% end %>
      </li>
      <li><%= link_to edit_flat_path(flat.id) do %>
        <i class="fas fa-edit"></i>
      <% end %>
    </li>
    </ul>
  </div>
<%end%>

app/views/flats/new.html.erb
<h1>New Flat</h1>

<%= render 'form', flat: @flat %>

<%= link_to 'Back', flats_path %>

app/views/flats/show.html.erb
  <div class="flat-one">
    <div class="product-upvotes">
      <!-- i.fa.fa-caret-up -->
      <i class="fa fa-caret-up"></i>
      <p>29</p>
    </div>
    <img src="https://source.unsplash.com/random/250x250" alt="">
    <div class="product-description">
      <h3><%= @flat.name %></h3>
      <p><%= @flat.description %></p>
      <p><%= @flat.price_per_night %>$</p>
    </div>
    <ul class="list-inline">
      <!-- (li>a)*3 -->

      <li><%= link_to "Back", root_path,  class: "btn-small" %>
      </li>
      <li><%= link_to flat_path(@flat.id), method: :delete do %>
        <i class="fas fa-trash"></i>
      <% end %>
      </li>
      <li><%= link_to edit_flat_path(@flat.id) do %>
        <i class="fas fa-edit"></i>
      <% end %>
    </li>
    </ul>
  </div>

<hr>


<div class="rev">
<h3>Reviews:</h3>

<% if @flat.reviews.empty? %>
  <p>There are no reviews yet.</p>
<% else %>
  <ul class="list-group">
    <% @flat.reviews.reverse.each do |review| %>
      <li class="list-group-item">
        <%= review.content %>
         <% for i in (1..review.rating.to_i) do %>
         <i class="fas fa-star" align="right"></i>
         <% end %>

         <%= link_to flat_review_path(@flat.id, review.id), method: :delete do %>
        <i class="fas fa-trash"></i>
      <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

<p>Add a new review:</p>

<%= simple_form_for [ @flat, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>

</div>

app/views/flats/update.html.erb
<h1>Flats#update</h1>
<p>Find me in app/views/flats/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <!-- [...] -->
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Messages", "#", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>
    <%= yield %>

  </body>
</html>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>